apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test1
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx      

---

apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: test1
spec:
  containers:
  - name: busybox
    image: busybox:1.32
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always  
